/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarenteam2;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author salma
 */
public class Försäljningsstatistik extends javax.swing.JFrame {
 private static InfDB idb;

    /**
     * Creates new form Försäljningsstatistik
     */
    public Försäljningsstatistik(InfDB idb) {
        initComponents();
        this.idb= idb;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDatumFrån = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDatumTill = new javax.swing.JTextField();
        btnSök = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBestallning = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        AntalOrdrar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nummerBx = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sokResult = new javax.swing.JTextArea();
        sok = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        visa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        visaResult = new javax.swing.JTextArea();
        senast = new javax.swing.JButton();
        datum1 = new javax.swing.JTextField();
        datum2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        backBtnKund = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDf = new javax.swing.JTextField();
        txtDt = new javax.swing.JTextField();
        jComboBoxHattar = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        AntalOrdrar1 = new javax.swing.JTextField();
        btnSök1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableLagerHattar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Försäljningsstatistik");

        jLabel3.setText("Sök fram alla ordrar registrerade mellan två datum!");

        jLabel4.setText("Från:");

        txtDatumFrån.setText("ÅÅÅÅ-MM-DD");

        jLabel5.setText("Tilll:");

        txtDatumTill.setText("ÅÅÅÅ-MM-DD");

        btnSök.setText("Sök");
        btnSök.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSökActionPerformed(evt);
            }
        });

        jTableBestallning.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "KundID", "SpecialhattID", "Orderdatum", "OrderStatus"
            }
        ));
        jScrollPane1.setViewportView(jTableBestallning);

        jLabel2.setText("Antal Ordrar:");

        AntalOrdrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntalOrdrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtDatumFrån, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtDatumTill, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(220, 260, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AntalOrdrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSök)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDatumFrån, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtDatumTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AntalOrdrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSök))
                .addGap(350, 350, 350))
        );

        jTabbedPane1.addTab("Specialhattar", jPanel1);

        jLabel6.setText("Sök fram statistik för alla kund ordrar eller för en specifik ");

        nummerBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nummerBxActionPerformed(evt);
            }
        });

        jLabel7.setText("Sök via telefon");

        sokResult.setColumns(20);
        sokResult.setRows(5);
        jScrollPane2.setViewportView(sokResult);

        sok.setText("Sök");
        sok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokActionPerformed(evt);
            }
        });

        jLabel8.setText("Visa allt:");

        visa.setText("Visa");
        visa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaActionPerformed(evt);
            }
        });

        visaResult.setColumns(20);
        visaResult.setRows(5);
        jScrollPane3.setViewportView(visaResult);

        senast.setText("OrderByLatest");
        senast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senastActionPerformed(evt);
            }
        });

        datum1.setText("ÅÅÅÅ-MM-DD");

        datum2.setText("ÅÅÅÅ-MM-DD");

        jLabel9.setText("Datum");

        backBtnKund.setText("Back");
        backBtnKund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnKundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nummerBx, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sok))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(datum1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datum2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(visa)
                        .addGap(18, 18, 18)
                        .addComponent(senast))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtnKund)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(datum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nummerBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sok)
                    .addComponent(visa)
                    .addComponent(senast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtnKund)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kund", jPanel2);

        jLabel10.setText("Sök fram alla försäljning av lagerförda hattar mellan två datum!");

        jLabel11.setText("Från:");

        jLabel12.setText("Till:");

        txtDf.setText("ÅÅÅÅ-MM-DD");
        txtDf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDfActionPerformed(evt);
            }
        });

        txtDt.setText("ÅÅÅÅ-MM-DD");
        txtDt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtActionPerformed(evt);
            }
        });

        jComboBoxHattar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filthatt", "Panamahatt", "Stråhatt", "Tyghatt", "Läderhatt" }));

        jLabel13.setText("Hatt:");

        jLabel14.setText("Antal Ordrar:");

        btnSök1.setText("Sök");
        btnSök1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSök1ActionPerformed(evt);
            }
        });

        jTableLagerHattar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KopID", "Produktnamn", "Pris", "Datum", "Lagerhatt"
            }
        ));
        jScrollPane4.setViewportView(jTableLagerHattar);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AntalOrdrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtDf, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSök1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxHattar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txtDf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxHattar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(AntalOrdrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSök1))
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Lagerfördahattar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSökActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSökActionPerformed
        // TODO add your handling code here:
        
         String Datumfrån = txtDatumFrån.getText();
         String Datumtill = txtDatumTill.getText();
        
        if(ValideringKlass.finnsVarde(txtDatumFrån)){
            
            try {
                
                String sqlFraga = "Select orderID, kundID, SpecialhattID, orderDatum, orderStatus from Ordrar  where orderDatum between '" + Datumfrån + "' and '" + Datumtill + "'";
                
                DefaultTableModel dTM = (DefaultTableModel) jTableBestallning.getModel();
                dTM.setRowCount(0);
                
                ArrayList<HashMap<String, String>> allInfoLista;
                allInfoLista = idb.fetchRows(sqlFraga);
                
                for(HashMap enOrder : allInfoLista){
                    Vector nyLista = new Vector();
                nyLista.add(enOrder.get("orderID"));
                nyLista.add(enOrder.get("kundID"));
                nyLista.add(enOrder.get("SpecialhattID"));
                nyLista.add(enOrder.get("orderDatum"));
                nyLista.add(enOrder.get("orderStatus"));
                dTM.addRow(nyLista);
                }
               
                String sqlFraga2 ="SELECT COUNT(orderID) FROM Ordrar;";
                String antal = idb.fetchSingle(sqlFraga2);
                AntalOrdrar.setText((antal) + "\n");
                
            } catch(InfException ex){
                JOptionPane.showMessageDialog(null, "Sökningen misslyckades, försök igen.");
                System.out.println("Internt felmeddeland" + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Datum måste fyllas i");
        }
        
    }//GEN-LAST:event_btnSökActionPerformed

    private void sokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokActionPerformed
        // söker fram efter telefonnummer
   try {
    String telefonVariable = nummerBx.getText();
    String telefonFraga = "SELECT kundID, kundNamn, adress, telefonNummer, epost, beskrivning FROM kund WHERE telefonNummer = '" + telefonVariable + "'";
    ArrayList<HashMap<String, String>> telefonResult = idb.fetchRows(telefonFraga);

    String kundIDFraga = "SELECT kundID FROM kund WHERE telefonNummer = '" + telefonVariable + "'";
    String kundIDResult = idb.fetchSingle(kundIDFraga);

    String orderFraga = "SELECT orderID, kundID, orderDatum, orderStatus, pris FROM ordrar WHERE kundID =" + kundIDResult + "";
    ArrayList<HashMap<String, String>> orderResult = idb.fetchRows(orderFraga);

    // Display the results in a formatted way
    StringBuilder sb = new StringBuilder();

    sb.append(String.format("%-10s %-15s %-15s %-15s %-25s %-15s\n", "kundID", "kundNamn", "adress", "telefonNummer", "epost", "beskrivning"));
    for (HashMap<String, String> row : telefonResult) {
        sb.append(String.format("%-10s %-15s %-15s %-15s %-25s %-15s\n", row.get("kundID"), row.get("kundNamn"), row.get("adress"), row.get("telefonNummer"), row.get("epost"), row.get("beskrivning")));
    }

    sb.append("\n");

    sb.append(String.format("%-10s %-10s %-15s %-15s %-10s\n", "orderID", "kundID", "orderDatum", "orderStatus", "pris"));
    for (HashMap<String, String> row : orderResult) {
        sb.append(String.format("%-10s %-10s %-15s %-15s %-10s\n", row.get("orderID"), row.get("kundID"), row.get("orderDatum"), row.get("orderStatus"), row.get("pris")));
    }

    String currentText = sokResult.getText();
    sokResult.setText(sb.toString());

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_sokActionPerformed

    private void visaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaActionPerformed
        // TODO add your handling code here:
   try {
    String kundFraga;
    String datum1Text = datum1.getText();
    String datum2Text = datum2.getText();
    if (!datum1Text.isEmpty() && !datum2Text.isEmpty()) {
        kundFraga = "SELECT kundID, kundNamn, adress, telefonNummer, epost, beskrivning FROM kund WHERE kundID IN (SELECT kundID FROM ordrar WHERE orderDatum BETWEEN '" + datum1Text + "' AND '" + datum2Text + "')";
    } else {
        kundFraga = "SELECT kundID, kundNamn, adress, telefonNummer, epost, beskrivning FROM kund";
    }
    ArrayList<HashMap<String, String>> kundResult = idb.fetchRows(kundFraga);

    StringBuilder sb = new StringBuilder();
    int count = 1;

    for (HashMap<String, String> row : kundResult) {
        sb.append(count + ". ");
        sb.append("Kund:\n");
        sb.append(String.format("%-6s %-6s %-12s %-12s %-30s %-20s\n", "kundID", "kundNamn", "adress", "telefonNummer", "epost", "beskrivning"));
        sb.append(String.format("%-6s %-6s %-12s %-12s %-30s %-20s\n", row.get("kundID"), row.get("kundNamn"), row.get("adress"), row.get("telefonNummer"), row.get("epost"), row.get("beskrivning")));

        String orderFraga;
        if (!datum1Text.isEmpty() && !datum2Text.isEmpty()) {
            orderFraga = "SELECT orderID, kundID, orderDatum, orderStatus, pris FROM ordrar WHERE kundID =" + row.get("kundID") + " AND orderDatum BETWEEN '" + datum1Text + "' AND '" + datum2Text + "'";
        } else {
            orderFraga = "SELECT orderID, kundID, orderDatum, orderStatus, pris FROM ordrar WHERE kundID =" + row.get("kundID");
        }
        ArrayList<HashMap<String, String>> orderResult = idb.fetchRows(orderFraga);

        sb.append("Order:\n");
        sb.append(String.format("%-8s %-8s %-15s %-12s %-6s\n", "orderID", "kundID", "orderDatum", "orderStatus", "pris"));
        for (HashMap<String, String> orderRow : orderResult) {
            sb.append(String.format("%-8s %-8s %-15s %-12s %-6s\n", orderRow.get("orderID"), orderRow.get("kundID"), orderRow.get("orderDatum"), orderRow.get("orderStatus"), orderRow.get("pris")));
        }
        sb.append("\n");
        count++;
    }

    visaResult.setText(sb.toString());

} catch(Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_visaActionPerformed

    private void nummerBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nummerBxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nummerBxActionPerformed

    private void senastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senastActionPerformed
        // TODO add your handling code here:
        try {
    String kundFraga = "SELECT k.kundID, k.kundNamn, k.adress, k.telefonNummer, k.epost, k.beskrivning " +
                       "FROM kund k " +
                       "JOIN ordrar o ON k.kundID = o.kundID " +
                       "ORDER BY o.orderDatum DESC";

    ArrayList<HashMap<String, String>> kundResult = idb.fetchRows(kundFraga);

    StringBuilder sb = new StringBuilder();
    int count = 1;

    for (HashMap<String, String> row : kundResult) {
        sb.append(count + ". ");
        sb.append("Kund:\n");
        sb.append(String.format("%-6s %-6s %-12s %-12s %-30s %-20s\n", "kundID", "kundNamn", "adress", "telefonNummer", "epost", "beskrivning"));
        sb.append(String.format("%-6s %-6s %-12s %-12s %-30s %-20s\n", row.get("kundID"), row.get("kundNamn"), row.get("adress"), row.get("telefonNummer"), row.get("epost"), row.get("beskrivning")));

        String orderFraga = "SELECT orderID, kundID, orderDatum, orderStatus, pris FROM ordrar WHERE kundID =" + row.get("kundID");
        ArrayList<HashMap<String, String>> orderResult = idb.fetchRows(orderFraga);

        sb.append("Order:\n");
        sb.append(String.format("%-8s %-8s %-15s %-12s %-6s\n", "orderID", "kundID", "orderDatum", "orderStatus", "pris"));
        for (HashMap<String, String> orderRow : orderResult) {
            sb.append(String.format("%-8s %-8s %-15s %-12s %-6s\n", orderRow.get("orderID"), orderRow.get("kundID"), orderRow.get("orderDatum"), orderRow.get("orderStatus"), orderRow.get("pris")));
        }
        sb.append("\n");
        count++;
    }

    //String currentText = visaResult.getText();
    visaResult.setText( sb.toString());

} catch(Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_senastActionPerformed

    private void txtDfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDfActionPerformed

    private void btnSök1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSök1ActionPerformed
        // TODO add your handling code here:
         String Datumfrån = txtDf.getText();
         String Datumtill = txtDt.getText();
        
        if(ValideringKlass.finnsVarde(txtDf)){
         try {

            String hattTypen = jComboBoxHattar.getSelectedItem().toString();
            String hämtaID = "Select lagerhattID from lagerfordahattar where typ = '" + hattTypen + "'";
            String ID = idb.fetchSingle(hämtaID);

            
            DefaultTableModel dTM = (DefaultTableModel) jTableLagerHattar.getModel();
            dTM.setRowCount(0);
        
            String sqlFraga = "Select kopID, Produktnamn, Pris, Datum, lagerhatt from kop where lagerhatt = '" + ID + "' and Datum between '" + Datumfrån + "' and '" + Datumtill + "'";
        
        
        ArrayList<HashMap<String, String>> hattLista;
        hattLista = idb.fetchRows(sqlFraga);
        
        for(HashMap enHatt : hattLista){
                Vector nyLista = new Vector(); 
                nyLista.add(enHatt.get("kopID"));
                nyLista.add(enHatt.get("Produktnamn"));
                nyLista.add(enHatt.get("Pris"));
                nyLista.add(enHatt.get("Datum"));
                nyLista.add(enHatt.get("lagerhatt"));

                dTM.addRow(nyLista);
                    
        } 
                String sqlFraga2 ="SELECT Count(kopID)FROM kop where lagerhatt = '" + ID + "' and Datum between '" + Datumfrån + "' and '" + Datumtill + "'"; 
                String antal = idb.fetchSingle(sqlFraga2);
                AntalOrdrar1.setText((antal) + "\n");
                
            } catch(InfException ex){
                JOptionPane.showMessageDialog(null, "Sökningen misslyckades, försök igen.");
                System.out.println("Internt felmeddeland" + ex.getMessage());
            }
         
         } else {
            JOptionPane.showMessageDialog(null, "Datum måste fyllas i");
        }
        
    }//GEN-LAST:event_btnSök1ActionPerformed

    private void txtDtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtActionPerformed

    private void AntalOrdrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntalOrdrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AntalOrdrarActionPerformed

    private void backBtnKundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnKundActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new ProgramStart().setVisible(true);
    }//GEN-LAST:event_backBtnKundActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Försäljningsstatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Försäljningsstatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Försäljningsstatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Försäljningsstatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AntalOrdrar;
    private javax.swing.JTextField AntalOrdrar1;
    private javax.swing.JButton backBtnKund;
    private javax.swing.JButton btnSök;
    private javax.swing.JButton btnSök1;
    private javax.swing.JTextField datum1;
    private javax.swing.JTextField datum2;
    private javax.swing.JComboBox<String> jComboBoxHattar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableBestallning;
    private javax.swing.JTable jTableLagerHattar;
    private javax.swing.JTextField nummerBx;
    private javax.swing.JButton senast;
    private javax.swing.JButton sok;
    private javax.swing.JTextArea sokResult;
    private javax.swing.JTextField txtDatumFrån;
    private javax.swing.JTextField txtDatumTill;
    private javax.swing.JTextField txtDf;
    private javax.swing.JTextField txtDt;
    private javax.swing.JButton visa;
    private javax.swing.JTextArea visaResult;
    // End of variables declaration//GEN-END:variables
}
