/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarenteam2;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException; 
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class HamtaKundInfo extends javax.swing.JFrame {
private InfDB idb;
    /**
     * Creates new form HamtaKundInfo
     */
    public HamtaKundInfo(InfDB idb) {
        this.idb = idb;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldKundID = new javax.swing.JTextField();
        okKnapp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKundData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hämta kunddata");

        jLabel2.setText("Kund ID: ");

        jTextFieldKundID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKundIDActionPerformed(evt);
            }
        });

        okKnapp.setText("OK");
        okKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okKnappActionPerformed(evt);
            }
        });

        jTableKundData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kund ID", "Namn", "Adress", "Telefonnummer", "Hederskund", "Epost"
            }
        ));
        jScrollPane1.setViewportView(jTableKundData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldKundID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(okKnapp)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldKundID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okKnapp)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldKundIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKundIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKundIDActionPerformed

    private void okKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okKnappActionPerformed
        // TODO add your handling code here:
        //valideringen:
        
        if(ValideringKlass.finnsVarde(jTextFieldKundID)){
            
            try {
        
        //Inmatning av kund id som man vill ha data från     
        String kundID = jTextFieldKundID.getText();
        //Omvandla inmatning som sträng till en int för att hämta ut ID:et från databasen.
        int intID = Integer.parseInt(kundID);
        
        String sqlFraga = "Select kundID, kundNamn, adress, telefonNummer, hedersKund, epost from Kund where kundID = " +  intID + "";
        
        DefaultTableModel dTM = (DefaultTableModel) jTableKundData.getModel();
        dTM.setRowCount(0);
        
         //Skapande av  hashmap för att lista kundID:en och respektive namn.
        ArrayList<HashMap<String, String>> allInfoLista; 
        allInfoLista = idb.fetchRows(sqlFraga);
        
 
            //
            //Loopa igenom allInfoLista för att sedan adda dessa rader som visas i J-framen. 
            for(HashMap enKund : allInfoLista){
                Vector nyLista = new Vector(); //Vector rekommenderades istället för arraylist därav valet.
                nyLista.add(enKund.get("kundID"));
                nyLista.add(enKund.get("kundNamn"));
                nyLista.add(enKund.get("adress"));
                nyLista.add(enKund.get("telefonNummer"));
                nyLista.add(enKund.get("hedersKund"));
                nyLista.add(enKund.get("epost"));
                dTM.addRow(nyLista);
                      
            }
        
      
        } catch (InfException ex){
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("Error: " + ex);
        }
            
            
            
            
            
            
            
        } else {
            JOptionPane.showMessageDialog(null, "KundID måste fyllas i");
        }
    }//GEN-LAST:event_okKnappActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HamtaKundInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HamtaKundInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HamtaKundInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HamtaKundInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKundData;
    private javax.swing.JTextField jTextFieldKundID;
    private javax.swing.JButton okKnapp;
    // End of variables declaration//GEN-END:variables
}
