/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarenteam2;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author axelbrave
 */
public class RegOrder extends javax.swing.JFrame {

      private InfDB idb;

    public RegOrder(InfDB idb) {
        this.idb= idb;
        initComponents();
        hamtaHatt ();
        hamtaKund ();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrderDatumTxt = new javax.swing.JTextField();
        comboHatt = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        boxKund = new javax.swing.JComboBox<>();
        NyOrderLabel = new javax.swing.JLabel();
        KIDLabel = new javax.swing.JLabel();
        OStatusLabel = new javax.swing.JLabel();
        OStatusComboBox = new javax.swing.JComboBox<>();
        ODatumLabel = new javax.swing.JLabel();
        SkapaOrderBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OrderDatumTxt.setText("20XX-XX-XX");

        jLabel1.setText("Hatt:");

        NyOrderLabel.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 24)); // NOI18N
        NyOrderLabel.setText("Ny Order");

        KIDLabel.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 13)); // NOI18N
        KIDLabel.setText("Kund:");

        OStatusLabel.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 13)); // NOI18N
        OStatusLabel.setText("Order Status:");

        OStatusComboBox.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 13)); // NOI18N
        OStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ej påbörjad", "påbörjad", "avslutad" }));

        ODatumLabel.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 13)); // NOI18N
        ODatumLabel.setText("Order Datum: ");

        SkapaOrderBtn.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 18)); // NOI18N
        SkapaOrderBtn.setText("Skapa Order");
        SkapaOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkapaOrderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(NyOrderLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(KIDLabel)
                                .addComponent(jLabel1))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboHatt, 0, 168, Short.MAX_VALUE)
                                .addComponent(boxKund, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(OStatusLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(OStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(ODatumLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(OrderDatumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(SkapaOrderBtn)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NyOrderLabel)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KIDLabel)
                    .addComponent(boxKund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboHatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OStatusLabel)
                    .addComponent(OStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderDatumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ODatumLabel))
                .addGap(35, 35, 35)
                .addComponent(SkapaOrderBtn)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SkapaOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkapaOrderBtnActionPerformed
        // TODO add your handling code here:
        try{
            idb=new InfDB("hattProjektet", "3306","hattProjektet","hattkey");
            String OrderID = idb.getAutoIncrement("ordrar", "orderID") ;
            String kundID = boxKund.getSelectedItem().toString();
            String hattID = comboHatt.getSelectedItem().toString();
            String orderStatus = OStatusComboBox.getSelectedItem().toString();
            String orderDatum = OrderDatumTxt.getText();         
            String fraga = "insert into ordrar values(" +OrderID+"," + kundID + "," + hattID + ",'" + orderStatus + "','" + orderDatum + "');";

            idb.insert(fraga);
            
            //  JOptionPane.showMessageDialog(null, fraga);
            
            //if (ValideringKlass.finnsVarde(KIDTxt) || ValideringKlass.finnsVarde(IDHatt1Txt) || ValideringKlass.finnsVarde(IDHatt2Txt) || ValideringKlass.finnsVarde(IDHatt3Txt) || ValideringKlass.finnsVarde(OrderDatumTxt) || ValideringKlass.finnsVarde(OStatusComboBox))
            //{}


            JOptionPane.showMessageDialog(null, "Ny specialhatt har registrerats!");

        }
        catch(InfException ettUndantag){
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }

    }//GEN-LAST:event_SkapaOrderBtnActionPerformed

    
    private void hamtaHatt () {
 
        String fraga = " Select namn from specialHattar" ; 
        
            ArrayList<String> hattar;
        
            try {
             
                 hattar = idb.fetchColumn(fraga);
                
           for (String enhatt : hattar){
                                 
                     comboHatt.addItem(enhatt);
                             }


            }
        
        
        catch (Exception e) {
            
        }
        
        
}
    
    
    
   private void hamtaKund () 
   {
      String hamtakund = "Select kundNamn from Kund"; 
      
                  ArrayList<String> Kunder;

       try {
             
                 Kunder = idb.fetchColumn(hamtakund);
                
           for (String enKund : Kunder){
                                 
                     boxKund.addItem(enKund);
                             }


            }
        
        
        catch (Exception e) {
            
        }
       
   }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KIDLabel;
    private javax.swing.JLabel NyOrderLabel;
    private javax.swing.JLabel ODatumLabel;
    private javax.swing.JComboBox<String> OStatusComboBox;
    private javax.swing.JLabel OStatusLabel;
    private javax.swing.JTextField OrderDatumTxt;
    private javax.swing.JButton SkapaOrderBtn;
    private javax.swing.JComboBox<String> boxKund;
    private javax.swing.JComboBox<String> comboHatt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
